server:
  port: 8000

zuul:
  routes:
    myworkspace:
      path: /myworkspace/**
      #url: http://localhost:9090
      serviceId: myworkspace
    gbus:
      path: /gbus/**
      url: http://localhost:9092
      
endpoints:
  routes:
    sensitive: false
  trace:
    sensitive: false


#ribbon:
#  eureka:
#    enabled: false

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka              